export const NAVIGATION_SCREENS = {
  AUTH_STACK: 'AuthStack',
  APP_STACK: 'AppStack',
  ONBOARDING: 'Onboarding',
  LOGIN: 'Login',
  CREATE_ACCOUNT: 'CreateAccount',
  OTP_VERIFICATION: 'OTPVerification',
  KYC: 'KYC',
  FORGOT_PASSWORD: 'ForgotPassword',
  FORGOT_PASSWORD_VERIFICATION: 'ForgotPasswordVerification',
  DASHBOARD_TAB: 'DashboardTab',
  CRYPTO_TAB: 'CryptoTab',
  TRANSACTIONS_TAB: 'TransactionsTab',
  WALLET_TAB: 'WalletTab',
  SETTINGS_TAB: 'SettingsTab',
  DASHBOARD: 'Dashboard',
  PROFILE: 'Profile',
  CRYPTO_LIST: 'CryptoList',
  CRYPTO_DETAILS: 'CryptoDetails',
  BUY_CRYPTO: 'BuyCrypto',
  SELL_CRYPTO: 'SellCrypto',
  TRANSACTION_HISTORY: 'TransactionHistory',
  TRANSACTION_DETAILS: 'TransactionDetails',
  WALLET: 'Wallet',
  ADD_FUNDS: 'AddFunds',
  WITHDRAW_FUNDS: 'WithdrawFunds',
  SETTINGS: 'Settings',
  SECURITY: 'Security',
  NOTIFICATIONS: 'Notifications',
} as const;

export type NavigationScreen = typeof NAVIGATION_SCREENS[keyof typeof NAVIGATION_SCREENS];
