import { StyleSheet } from "react-native";
import { ITheme } from "@new-ui/styles/themes/themeTypes";

export const locationFinderStyles = (theme: ITheme) =>
  StyleSheet.create({
    searchHeaderOuter: {
      zIndex: 100,
      elevation: 12,
    },
    container: {
      flex: 1,
      backgroundColor: theme.colors.black,
    },
    map: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 0,
    },
    searchHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.base,
      paddingTop: theme.spacing["4xl"],
      gap: theme.spacing.sm,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    searchInputWrap: {
      flex: 1,
      borderRadius: 18,
      backgroundColor: theme.colors.surfaceElevated,
      paddingHorizontal: theme.spacing.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      minHeight: 40,
      justifyContent: "center",
    },
    searchInput: {
      color: theme.colors.text,
      fontFamily: theme.typography.fontFamily.poppinsRegular,
      fontSize: 14,
      paddingVertical: 0,
    },
    suggestionsWrap: {
      marginTop: theme.spacing.xs,
      marginHorizontal: theme.spacing.base,
      maxHeight: 240,
      borderRadius: theme.radius.lg,
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: "hidden",
    },
    suggestionRow: {
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    suggestionMain: {
      fontFamily: theme.typography.fontFamily.poppinsRegular,
      fontSize: 14,
      color: theme.colors.text,
    },
    suggestionSub: {
      marginTop: 2,
      fontFamily: theme.typography.fontFamily.poppinsRegular,
      fontSize: 12,
      color: theme.colors.greyDark,
    },
    placesErrorText: {
      marginTop: theme.spacing.xs,
      marginHorizontal: theme.spacing.base,
    },
    fetchingOverlay: {
      position: "absolute",
      top: 120,
      alignSelf: "center",
      padding: theme.spacing.sm,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.overlay,
    },
    emptyNearbyWrap: {
      position: "absolute",
      left: theme.spacing.lg,
      right: theme.spacing.lg,
      bottom: 170,
      padding: theme.spacing.md,
      borderRadius: theme.radius.lg,
      backgroundColor: "rgba(10, 11, 56, 0.92)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
    },
    filterButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    markerWrap: {
      alignItems: "center",
      justifyContent: "center",
    },
    markerDot: {
      minWidth: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 6,
      borderWidth: 2,
      borderColor: theme.colors.background,
    },
    carouselWrap: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: theme.spacing.xl,
    },
    carouselContent: {
      paddingHorizontal: theme.spacing.lg,
      columnGap: theme.spacing.md,
    },
    locationCard: {
      width: 290,
      borderRadius: theme.radius.xl,
      backgroundColor: "rgba(10, 11, 56, 0.95)",
      padding: theme.spacing.lg,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
      gap: theme.spacing.xs,
    },
    locationCardSelected: {
      borderColor: theme.colors.primary,
    },
    locationCardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    locationAddress: {
      opacity: 0.8,
    },
    locationHours: {
      marginBottom: theme.spacing.md,
    },
    sellCodeBlock: {
      marginTop: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.radius.md,
      backgroundColor: "rgba(255,255,255,0.08)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
    },
    sellCodeLabel: {
      marginBottom: theme.spacing.xs,
      opacity: 0.85,
    },
    sellCodeValue: {
      fontFamily: theme.typography.fontFamily.poppinsRegular,
    },
    sellMoreDetailsWrap: {
      marginTop: theme.spacing.md,
    },
    stateWrap: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 170,
      alignItems: "center",
      justifyContent: "center",
    },
  });
