export const TYPOGRAPHY = {
  fontFamily: {
    regular: 'Montserrat-Regular',
    medium: 'Montserrat-Medium',
    semiBold: 'Montserrat-SemiBold',
    bold: 'Montserrat-Bold',
    poppinsThin: 'Poppins-Thin',
    poppinsExtraLight: 'Poppins-ExtraLight',
    poppinsLight: 'Poppins-Light',
    poppinsRegular: 'Poppins-Regular',
    poppinsMedium: 'Poppins-Medium',
    poppinsSemiBold: 'Poppins-SemiBold',
    poppinsBold: 'Poppins-Bold',
    poppinsExtraBold: 'Poppins-ExtraBold',
    poppinsBlack: 'Poppins-Black',
    poppinsThinItalic: 'Poppins-ThinItalic',
    poppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
    poppinsLightItalic: 'Poppins-LightItalic',
    poppinsItalic: 'Poppins-Italic',
    poppinsMediumItalic: 'Poppins-MediumItalic',
    poppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
    poppinsBoldItalic: 'Poppins-BoldItalic',
    poppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    poppinsBlackItalic: 'Poppins-BlackItalic',
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 28,
    '4xl': 32,
  },
  lineHeight: {
    tight: 1.2,
    normal: 1.5,
    relaxed: 1.75,
  },
  fontWeight: {
    regular: '400',
    medium: '500',
    semiBold: '600',
    bold: '700',
  },
} as const;

